### ISSUE TITLE
Doesn't work after IndieGala's frontend update

### ISSUE THREAD

**Issue by EustaceCS** [burnhamup/galaxy-integration-indiegala#1]
They just updated their frontend so the plugin can't recognize the data needed for library sync.
This, or login with Google doesn't work anymore :(
Logs:
https://drive.google.com/file/d/1RvoB-ZM1_F2FYscwV0B1qBGt5xHoGTS7/view?usp=sharing

**Comment by burnhamup** [comment]
Confirmed - this update has removed the endpoints I was using to retrieve user info and the list of freebies. What bad timing on my part. 

I'll start poking around, but it looks like I have to start from scratch.

**Comment by burnhamup** [comment]
I've got a new release out that should be working at least as well as the old one. 

I'm able to pull my games again after updating.
