### ISSUE TITLE
Installation Instructions?

### ISSUE THREAD

**Issue by michaelwexler** [burnhamup/galaxy-integration-indiegala#10]
I created a dir, put in the files, but GOG didn't seem to recognize the plugin.  Is there an extra step missing from the Readme?

**Comment by burnhamup** [comment]
Have you restarted GOG Galaxy? That will force it to look for new plugins in the folders

**Comment by michaelwexler** [comment]
Fair point.  GOG hides in the "tray" by default.  So, shutting down GOG completely, then following the directions in the readme.md, I was able to get this plugin to show up.  

It was very manual, so somewhere along the way, would be nice to have a bit more packaging to automate some of this... but congrats, in my test, it did pull down the list of my currently owned "showcase" games.

**Comment by michaelwexler** [comment]
Closed, issue was user error.
