### ISSUE TITLE
Can't login with Google

### ISSUE THREAD

**Issue by Levian-X** [burnhamup/galaxy-integration-indiegala#12]
After logging in with Google, the plug-in shows my Google-name and immediately goes offline.

I'm using the latest release 0.0.8.

**Comment by BuryTomorrow12** [comment]
Same issue, same version.

It doesn't even generate a logfile on the logs folder...

**Comment by burnhamup** [comment]
The new release https://github.com/burnhamup/galaxy-integration-indiegala/releases/tag/0.1.0 uses a different method for login/data retrieval which should address this issues.
