### ISSUE TITLE
Indiegala window steals focus when opening

### ISSUE THREAD

**Issue by piber20** [burnhamup/galaxy-integration-indiegala#13]
When the integration opens the indiegala window to reestablish the connection, it steals the focus out of fullscreen games, minimizing them and causing a very frustrating interruption. Experienced with Gunfire Reborn.

**Comment by seedie** [comment]
I also have this problem. The security check seems to happen often too.

**Comment by burnhamup** [comment]
I've seen it too, but I don't know why it's happening. 

My plugin reports a lost connection, and sometimes Galaxy will just disable the integration, and sometimes it will attempt to re-authenticate. 

I still haven't been able to get good feedback from them about how to handle these captchas.

**Comment by b1oki** [comment]
I also have this issue a few times a day.

**Comment by mortenanakin** [comment]
Me too. Its specially annoying when im playing o watching a movie in full screen :(

**Comment by Kuki77** [comment]
Here the same issue. Very annoying during gameplay!

**Comment by Kuki77** [comment]
Is this integration abandoned?

**Comment by burnhamup** [comment]
Yeah, it's mostly abandoned. Indiegala uses a anti-bot system that blocks things like this integration from working. 
I tried to get around it with https://github.com/ziplokk1/incapsula-cracker-py3 and ended up with at least a temp ban inside of my Galaxy. 

The window popup is Galaxy itself attempting to reauthenticate, and I don't have much control over what they decide to do.

**Comment by jakopo87** [comment]
Have a look at my fork: it saves download urls on file and they work without authentication, but if you add new games you have to disconnect & reconnect the extension

**Comment by Kuki77** [comment]
@jakopo87 
I just realized, that I already had your fork in usage and the issue with the popup is with your version.

**Comment by jakopo87** [comment]
@Kuki77 
I had some local changes not committed to the repository, now the popup should not appear as long as long as the `data_cache` folder is present.
At the moment it never gets deleted, so for new games it must be done manually, i'll have to look if it can be done when you disconnect manually and not when you close down the whole client

**Comment by Kuki77** [comment]
Hmm. With the current version of your plugin, @jakopo87, no Indiegala games from Indiegala (not installed) are listed anymore.
I reconnected / reauthentificated ... but nothing.

**Comment by jakopo87** [comment]
I know, probably because the task that reports OS compatibility gets called after a long time

**Comment by Kuki77** [comment]
OK, I had also to delete manually the corresponding database file under C:\ProgramData\GOG.com\Galaxy\storage\plugins\
 and then the games have been loaded.

**Comment by mortenanakin** [comment]
> OK, I had also to delete manually the corresponding database file under C:\ProgramData\GOG.com\Galaxy\storage\plugins
> and then the games have been loaded.
> 
> I'll report if the popup is away in some days.
> 
> But one question:
> If I'll have new games in Indiegala library, will the plugin "detect" them somehow or do I have to delete the data again manually and redo the "full load"?

Sorry, how do you do it? I cant see "indiegala" appart in GOG anymore xD 
Exactly what files did you delete? :)

**Comment by jakopo87** [comment]
> OK, I had also to delete manually the corresponding database file under C:\ProgramData\GOG.com\Galaxy\storage\plugins\
>  and then the games have been loaded.
> 
> I'll report if the popup is away in some days.
> 
> But one question:
> If I'll have new games in Indiegala library, will the plugin "detect" them somehow or do I have to delete the data again manually and redo the "full load"?

Nope, manual delete is needed

**Comment by mortenanakin** [comment]
> > OK, I had also to delete manually the corresponding database file under C:\ProgramData\GOG.com\Galaxy\storage\plugins
> > and then the games have been loaded.
> > I'll report if the popup is away in some days.
> > But one question:
> > If I'll have new games in Indiegala library, will the plugin "detect" them somehow or do I have to delete the data again manually and redo the "full load"?
> 
> Nope, manual delete is needed

Exactly what files do i have to delete? :/

**Comment by Kuki77** [comment]
@mortenanakin 
First of all: This issue here (or better said, the current workaround discussion) is not about this addon here but about the fork made by jakopo87. See list of his repositories to find it.

I had to delete the data_cache folder in the addon folder but also the database file with the indiegala games in the folder C:\ProgramData\GOG.com\Galaxy\storage\plugins

If these two information are not sufficient for you, then better don't touch these things to not make it worse ;)

**Comment by jakopo87** [comment]
> > > OK, I had also to delete manually the corresponding database file under C:\ProgramData\GOG.com\Galaxy\storage\plugins
> > > and then the games have been loaded.
> > > I'll report if the popup is away in some days.
> > > But one question:
> > > If I'll have new games in Indiegala library, will the plugin "detect" them somehow or do I have to delete the data again manually and redo the "full load"?
> > 
> > Nope, manual delete is needed
> 
> Exactly what files do i have to delete? :/

They are not present in this extension, but in another I created from this one

**Comment by mortenanakin** [comment]
> @mortenanakin
> First of all: This issue here (or better said, the current workaround discussion) is not about this plugin here but about the fork made by jakopo87. See list of his repositories to find it.
> 
> I had to delete the data_cache folder in the plugin folder but also the database file with the indiegala games in the folder C:\ProgramData\GOG.com\Galaxy\storage\plugins
> 
> If these three information are not sufficient for you, then better don't touch these things to not make it worse ;)

I'm using jakopo's87 fork, dont worry for this :)

I havent data_cache folder in my plugin folder. I found it the database file and delete it :)

The thing is, of 46 games listed in indiegala, GOG only show me 13 :/ Any idea?

**Comment by mortenanakin** [comment]
> > > > OK, I had also to delete manually the corresponding database file under C:\ProgramData\GOG.com\Galaxy\storage\plugins
> > > > and then the games have been loaded.
> > > > I'll report if the popup is away in some days.
> > > > But one question:
> > > > If I'll have new games in Indiegala library, will the plugin "detect" them somehow or do I have to delete the data again manually and redo the "full load"?
> > > 
> > > 
> > > Nope, manual delete is needed
> > 
> > 
> > Exactly what files do i have to delete? :/
> 
> They are not present in this extension, but in another I created from this one

Then i must be doing something wrong, can you give me the link to you extension?

**Comment by mortenanakin** [comment]
> > > > OK, I had also to delete manually the corresponding database file under C:\ProgramData\GOG.com\Galaxy\storage\plugins
> > > > and then the games have been loaded.
> > > > I'll report if the popup is away in some days.
> > > > But one question:
> > > > If I'll have new games in Indiegala library, will the plugin "detect" them somehow or do I have to delete the data again manually and redo the "full load"?
> > > 
> > > 
> > > Nope, manual delete is needed
> > 
> > 
> > Exactly what files do i have to delete? :/
> 
> They are not present in this extension, but in another I created from this one

Then how can i get your extension? :)

**Comment by Kuki77** [comment]
@mortenanakin 
Go to Jacopos plugin repository, download it completely and extract it into an own subfolder into the plugins folder like it's described in the readme (there and here)

**Comment by mortenanakin** [comment]
Hell yeah! Now all my games are there, and no more popup window!

**Comment by liviux** [comment]
> Hell yeah! Now all my games are there, and no more popup window!

So what exactly did you do? Kept this plugin and added the fork or only the fork or what?

**Comment by mortenanakin** [comment]
> So what exactly did you do? Kept this plugin and added the fork or only the fork or what?

Only the fork :)

**Comment by liviux** [comment]
If I have only the fork it won't even start connecting, error starting plug-in, or something like that. I even cleaned everything old %localappdata%\GOG.com\Galaxy\plugins\installed\
 and 
%programdata%\GOG.com\Galaxy\storage\plugins\
This plugin works but annoying pop-up verification check randomly apperes

**Comment by burnhamup** [comment]
The new release https://github.com/burnhamup/galaxy-integration-indiegala/releases/tag/0.1.0 uses a different method for login/data retrieval which should address this issues.
