### ISSUE TITLE
Connection offline

### ISSUE THREAD

**Issue by Dr-Flay** [burnhamup/galaxy-integration-indiegala#14]
I can connect the plugin it seems but it disconnects and shows as offline straight away

[plugin-indiegala-a1a85742-f3e0-42ae-bde9-64ab7d0321cf.log](https://github.com/burnhamup/galaxy-integration-indiegala/files/5111897/plugin-indiegala-a1a85742-f3e0-42ae-bde9-64ab7d0321cf.log)

**Comment by DarkJuanFra** [comment]
Same happening to me! Any clue?
[plugin-indiegala-a1a85742-f3e0-42ae-bde9-64ab7d0321cf.log](https://github.com/burnhamup/galaxy-integration-indiegala/files/5166004/plugin-indiegala-a1a85742-f3e0-42ae-bde9-64ab7d0321cf.log)

**Comment by tamer82** [comment]
I debugged the script and found the issue. If you have white spaces in your username the script will fail and result in the error.
It's easy to fix in the code however, you can also change your indiegala username to remove the whitespace from it and it should work.

**Comment by DarkJuanFra** [comment]
@tamer82  Man, you're the best!! 
I was logging with FB, hence my FB name became my username, I changed it to one without spaces, and now it's connected!! <3 really thanks bro!!

**Comment by Dr-Flay** [comment]
My indiegala username does not have any spaces, it is;
Dr-Flay

**Comment by DarkJuanFra** [comment]
Hm, maybe the "-" would be annoying for the code as well... I'm guessing because there's no "" added to the variable that gather out Username. (Didn't debugged as Tamer, just guessing). 
Try changing your ID to something withouth any special character and let us know :)

**Comment by login0false** [comment]
Had this issue too. Fixed (or, rather, band-aided) by removing Cyrillic characters and replacing space with underscore (_) in my indiegala name..

**Comment by burnhamup** [comment]
The new release https://github.com/burnhamup/galaxy-integration-indiegala/releases/tag/0.1.0 uses a different method for login/data retrieval which should address this issues.

**Comment by Dr-Flay** [comment]
Confirmed
Issue now resolved.
