### ISSUE TITLE
Install games

### ISSUE THREAD

**Issue by Dark2g** [burnhamup/galaxy-integration-indiegala#16]
Maybe isn't an error but I can't install games of IndieGala using gog (they appear but the install buttom is unavailable... said that is incompatible)

I think it is caused by IndieGala haven't a platform like Epic or Origin, is it the possible cause?

SORRY IF ENGLISH IS BAD, I'M NOT ENGLISH SPEAKER AND I TRY MY BEST :)

**Comment by burnhamup** [comment]
Correct, installing games isn't supported by the plugin. It's tricky to do, and I can't begin to think about it until I get a stable connection to their site.
