### ISSUE TITLE
Indiegala plugin not syncing

### ISSUE THREAD

**Issue by Danyelalejandro** [burnhamup/galaxy-integration-indiegala#19]
I noticed froma few days that no new games were added. I disconnected and connected again and now no games appear.

**Comment by Danyelalejandro** [comment]
Update: I reinstalled it and it's not working anymore...

**Comment by burnhamup** [comment]
The new release https://github.com/burnhamup/galaxy-integration-indiegala/releases/tag/0.1.0 uses a different method for login/data retrieval which should address this issues.
