### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by Andronigma** [burnhamup/galaxy-integration-indiegala#20]
When connecting this integration it requests email, password, captia. With all those correct, the actual log in button can not be clicked. (it feels like the browser in galaxy app lacks the ability to work with the indiegala site)

**Comment by burnhamup** [comment]
The new release https://github.com/burnhamup/galaxy-integration-indiegala/releases/tag/0.1.0 uses a different method for login/data retrieval which should address this issues.
