### ISSUE TITLE
Last version only has source code but not installable zip

### ISSUE THREAD

**Issue by Danyelalejandro** [burnhamup/galaxy-integration-indiegala#21]
Hello and thank you for takinf he time in this development

Last release has just source code but not installement zip file. I know nothing about python or development, please help us to upload the installation zip file as you did with previous versions.

Thank you so much,

Daniel

**Comment by ghost** [comment]
Copying \src subfolder content from 0.1.0 archive right into previous plugin version directory
(which is expected to be at C:\Users\%YOUR USER NAME%\AppData\Local\GOG.com\Galaxy\plugins\installed\indiegala )
seems to work.

**Comment by Danyelalejandro** [comment]
It worked at the 4th time. Thank yu. Hope you may add some things in the future.

**Comment by Kissaki** [comment]
Would still be nice if the release had the file, like previous releases.

The workaround is just a workaround.

**Comment by burnhamup** [comment]
Oh, it had been so long I had forgotten to attach the release on GitHub. I've attached it now
