### ISSUE TITLE
Unknow games

### ISSUE THREAD

**Issue by eduonlinebr** [burnhamup/galaxy-integration-indiegala#24]
There's a lot of games on my gog galaxy 2.0 library that's shown as "unknown games" and all of then comes from indie gala. Please fix that. 
![image](https://user-images.githubusercontent.com/87217320/125150930-c0cca080-e119-11eb-923b-93a49c3c80af.png)

**Comment by jakopo87** [comment]
Game title and metadata are pulled from [IGDB](https://www.igdb.com) by the galaxy client, the extension can not control that. For unknown games you have to rename that manually or make an entry on IGDB.

**Comment by eduonlinebr** [comment]
I see, but Can you guess why all my games on galaxy client have title and thumbnails, while some lacks on my gog galaxy library? 
![image](https://user-images.githubusercontent.com/87217320/125178531-4e60cc80-e1bc-11eb-9232-5d8a0ddabbf0.png)

**Comment by jakopo87** [comment]
For the reason I wrote in my previous comment: GOG look up on IGDB and shows "Unknown game" if there is no match for a title.

**Comment by eduonlinebr** [comment]
It looks like when there's two or more games with the same title, the gog galaxy doesn't match it automatically, but thanks for the help!
