### ISSUE TITLE
Connects fine but it does not show any games at all.

### ISSUE THREAD

**Issue by MarkoH01** [burnhamup/galaxy-integration-indiegala#3]
I can connect to indiegala but all I see in Galaxy is an empty screen afterwards.

**Comment by burnhamup** [comment]
Just to be sure - when you visit https://www.indiegala.com/library/showcase/1 do you have any games listed there? This integration only syncs those showcases.

But I've got similar issues. I've noticed some new issue with IndieGala - they seemed to have added some cloud protection service that I need to figure out how to work with.

**Comment by EustaceCS** [comment]
It looks like that as a part of their frontend overhaul they removed quite a number of games from both Showcase and user accounts (for those who managed to add these freebies into their libraries).
https://freebies.indiegala.com/back-to-bed/ and https://freebies.indiegala.com/762-high-calibre/ game pages are still active but 'Download is not available'.
Weird.

**Comment by MarkoH01** [comment]
Now I tried v0.0.4 of the plugin and I can't connect anymore. The plugin tries to connect and ends immediately with the message "connection lost".

**Comment by jakopo87** [comment]
> 
> 
> It looks like that as a part of their frontend overhaul they removed quite a number of games from both Showcase and user accounts (for those who managed to add these freebies into their libraries).
> https://freebies.indiegala.com/back-to-bed/ and https://freebies.indiegala.com/762-high-calibre/ game pages are still active but 'Download is not available'.
> Weird.
> Dropped a mail to their customer support, will gladly share what they'll supply me with.

I still see the games in my account, but the pager is bugged: it does stop at page 4, but you can go further changing manually the page number in the url

**Comment by burnhamup** [comment]
The v.0.0.5 improves some of this connection lost stuff. But I'm still tying to understand how to play nice with their bot detection system. I also worked around their pager bug, which I hope doesn't bite me in the future.

**Comment by EustaceCS** [comment]
Got the response regarding missing titles like 7.62 and Back to Bed.
> We apologize for the inconvenience, our technicians are trying to fix this as soon as possible.
Well, at least we know that they _are_ aware of it now.

**Comment by MarkoH01** [comment]
Even with release 0.6 still connection lost - no games showing.

**Comment by EustaceCS** [comment]
NB: they fixed games missing from https://www.indiegala.com/library/showcase/ .
Game page (i. e. https://freebies.indiegala.com/brigade-e5-new-jagged-union/ ) still shows Download Not Available - but download links from Showcase do work.

**Comment by MarkoH01** [comment]
The 0.0.7 version finally fixed my problem. I can connect and Galaxy is showing Indigala games :)

**Comment by burnhamup** [comment]
I'm glad it's working now
