### ISSUE TITLE
IP check not detected

### ISSUE THREAD

**Issue by beer-matt** [burnhamup/galaxy-integration-indiegala#5]
I had (have) IP check left enabled in my profile, after connecting the plugin and logging in I received multiple "Indiegala - Account Verification" emails (I ended the GoG task to stop it).
After logging in using a browser & responding to the IP check I was then able to retry connecting the plugin, which then worked successfully..

**Comment by burnhamup** [comment]
Thank you for the report. I noticed the IP check during my initial research, but then haven't had it trigger. I should be able to detect the check to prevent the flood of emails. 

Do you know what the page looks like that asks for the code? If you or anyone else could post a screenshot, that would be very helpful. In the meantime, I'll see if I can change my IP address to trigger the check.

**Comment by burnhamup** [comment]
I got a sample of the HTML that gets displayed when the IP check happens.

This one is a trickier case to actually fix since I don't know how to trigger the check during login, or how to tell if the check has failed. At the very least I'll patch the plugin to stop the flood of emails.

**Comment by beer-matt** [comment]
Thanks - I've tested 0.0.6 and it does seem to detect the IP check page (plugin changes to Disconnected with only 1 email received); after logging in with a browser and responding to the IP check then selecting Connect again seems to work. 👍
If possible it would be good to bring up the challenge window (similar to other plugins - Steam, Humble Bundle etc.), as at the minute it changes to Disconnected with no indication as to why.

**Comment by sdrubble** [comment]
Testing 0.0.6 with Galaxy 2.0.15.43 here. I was getting the 'instant disconnection' from Galaxy without noticing the tsunami of emails from Indie Gala (got 411 of them to be exact), so in the investigation process I ended up testing 0.0.5 as well.

In the end I followed up the suggestion from the emails: temporarily DISABLING "IP VERIFICATION" in IG's account settings, then re-enabling it again after being sure that the integration was working. 

It seems that, after the FIRST stable connection from IG in Galaxy, re-enabling IP verification won't cause any further issues. I tested this by logging in and out of IG 3 times from a browser, as well as closing and restarting Galaxy 3 times as well.

**Comment by beer-matt** [comment]
I've just tested 0.0.7, and IP Check still causes the plugin to change to "Connection Lost"; after logging in & verifying from a browser the plugin then connects ok..

**Comment by beer-matt** [comment]
(apologies, didn't mean to close..)

**Comment by burnhamup** [comment]
I'm closing this issue in favor of issue #4 since "Connection Lost" is now a known issue that I'm not sure we'll be able to fix.
