### ISSUE TITLE
Images not displayed for all games in library

### ISSUE THREAD

**Issue by beer-matt** [burnhamup/galaxy-integration-indiegala#6]
Hopefully this demonstrates; I tried disconnecting & reconnecting and the same games appear to not have an image..
![GOG - IndieGala1](https://user-images.githubusercontent.com/20976033/81509185-c0abf780-9300-11ea-93e6-c6b7870dfdb5.png)

**Comment by burnhamup** [comment]
This is an issue with GOG Galaxy. My plugin provides a game name, and their system and database provides the images and all other data.
