### ISSUE TITLE
'Platform' icon too wide in List view

### ISSUE THREAD

**Issue by sdrubble** [burnhamup/galaxy-integration-indiegala#7]
Pretty much as stated in the title. When 'List' viewing games from all platforms together - after customizing List view in order to include the 'Platform Icon' column - the IndieGala icon is exaggeratedly wide, so the icons for IndieGala games become strongly misaligned to the left.

A side effect of this is: switch to Grid view, then hover the mouse above any IndieGala game. The overlay is also too wide (when compared to the overlays for non-IG games), and doesn't show the game NAME inside the overlay either.

**Comment by burnhamup** [comment]
This appear to be an issue with Galaxy itself - it may need to be updated with an actual icon. It doesn't look like anything I have control over.
