### ISSUE TITLE
I can't finish the login

### ISSUE THREAD

**Issue by RaptorPharaoh** [burnhamup/galaxy-integration-indiegala#9]
Hello, when I push the connect button, appears the Login screen, I can put my User, Password and resolve the captcha, when I push the send button the window closes and failed to connect, because I can't put the verification code sended by IndieGala :(

Please can you check this issue?

Thanks, have a good day. :)

**Comment by burnhamup** [comment]
This sounds like their IP check. I'll have to get some more information about how it works. If the window is closing it means I'm missing a step and closing the window too early.

**Comment by burnhamup** [comment]
I just pushed a new version 0.0.8 that should help.

**Comment by RaptorPharaoh** [comment]
> This sounds like their IP check. I'll have to get some more information about how it works. If the window is closing it means I'm missing a step and closing the window too early.



> I just pushed a new version 0.0.8 that should help.

Hello, thanks for the new version, the Plug-In works perfectly now.

**Comment by burnhamup** [comment]
Thanks for reporting back!
